name: local_pulse_citizen
description: "A civic engagement platform connecting citizens and authorities"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  
  # Location & Maps
  geolocator: ^10.1.1
  geocoding: ^2.2.2
  google_maps_flutter: ^2.13.1
  
  # Image & Camera
  image_picker: ^1.2.0
  image: ^4.3.0
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  
  # Local Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Networking
  http: ^1.5.0
  
  # UI & Utils
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
    background_color: "#1565C0"
    theme_color: "#1565C0"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"
    icon_size: 48